# Services that our application needs 

services:

  # PostgreSQL Database 
  postgres:

    # Official Docker image 

    image: postgres:17

    # Easy to identify container 

    container_name: ai-postgres

    # Restart automatically after system reboot 

    restart: unless-stopped

    # Initial database configuration 

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_interview

    # HostPort : ContainerPort 

    ports:
      - "5432:5432"

    # Persist database data 

    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq: 
    image: rabbitmq:3-management
    container_name: ai-rabbitmq
    restart: unless-stopped

    ports: 
      - "5672:5672" 
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    container_name: redis

    ports: 
      - "6379:6379"

    restart: unless-stopped

  redis-commander: 
    image: rediscommander/redis-commander
    container_name: redis-commander
    restart: unless-stopped

    ports: 
      - "8081:8081"

    environment:
      - REDIS_HOSTS=local:redis:6379

    depends_on: 
      - redis

  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.20
    container_name: ai-elasticsearch
    restart: unless-stopped

    environment: 
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.license.self_generated.type: trial 

    ports: 
      - "9200:9200"

    volumes: 
      - elasticsearch_data:/usr/share/elasticsearch/data

# Named Docker Volume 

volumes:
  postgres_data:
  elasticsearch_data: