export enum UserEventType {
  USER_REGISTERED = "USER_REGISTERED",
  RESEND_OTP = "RESEND_OTP",
  PASSWORD_RESET = "PASSWORD_RESET",
  ACCOUNT_DELETION_REQUESTED = "ACCOUNT_DELETION_REQUESTED",
}

export enum InterviewEventType {
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_UPDATED = "INTERVIEW_UPDATED",
  INTERVIEW_DELETED = "INTERVIEW_DELETED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
}