export enum UserEventType {
  USER_REGISTERED = "USER_REGISTERED",
  RESEND_OTP = "RESEND_OTP",
  PASSWORD_RESET = "PASSWORD_RESET",
}

export enum InterviewEventType {
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
}