import mongoose, { Document, Schema } from "mongoose";

export interface FileDocument extends Document {
    originalName: string;
    fileName: string;

    mimeType: string; // MIME type identifies the actual type of an uploaded file (e.g. image/png, application/pdf) - Used to validate and restrict allowed file uploads 

    extension: string;
    size: number;

    bucket: string; // S3 bucket is the top-level storage container in AWS S3 where uploaded files are stored. Files are organized inside folders (keys) within a bucket. 

    etag: string; // ETag is an unique identifier generated by S3 for an uploaded object. It helps verify upload integrity and identify a specific file version 

    key: string;
    url: string;
    uploadedBy?: string;
    isPublic: boolean;
}

const fileSchema = new Schema<FileDocument>(
    {
        originalName: {
            type: String, 
            required: true 
        }, 
        fileName: {
            type: String,
            required: true,
        },

        mimeType: {
            type: String,
            required: true,
        },

        extension: {
            type: String,
            required: true,
        },

        size: {
            type: Number,
            required: true,
        },

        bucket: {
            type: String,
            required: true,
        },key: {
            type: String,
            required: true,
            unique: true,
        },

        etag: {
            type: String, 
            required: true 
        },

        url: {
            type: String,
            required: true,
        },

        uploadedBy: {
            type: String,
        },
        isPublic: {
            type: Boolean,
            default: false,
        },
    },
    {
        timestamps: true 
    }
) ; 

export default mongoose.model<FileDocument>("File", fileSchema);